name: Automated Monthly Investment

on:
    schedule:
        - cron: "15 7 1 * *" # Runs monthly at 7:15 AM UTC on the 1st
    workflow_dispatch:

jobs:
    run_script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
                  cache: "pip"
                  cache-dependency-path: requirements.txt
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
            - name: Set up environment variables
              run: |
                  echo "MERCADO_BITCOIN_API_ID=${{ secrets.MERCADO_BITCOIN_API_ID }}" >> $GITHUB_ENV
                  echo "MERCADO_BITCOIN_API_SECRET=${{ secrets.MERCADO_BITCOIN_API_SECRET }}" >> $GITHUB_ENV
            - name: Run the script
              run: |
                  cd src
                  python main.py $SYMBOL $CURRENCY $COST
              env:
                  SYMBOL: ${{ vars.SYMBOL }}
                  CURRENCY: ${{ vars.CURRENCY }}
                  COST: ${{ vars.COST }}
            - name: Commit and Push JSON File
              if: success()
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  # Define the JSON file name
                  file_name="${SYMBOL}-${CURRENCY}-orders.json"
                  # Check if the file exists before committing
                  if [ -f "$file_name" ]; then
                      git add "$file_name"
                      git commit -m "Add order details for ${{ vars.SYMBOL }}-${{ vars.CURRENCY }}"
                      git push origin main
                  else
                      echo "JSON file $file_name not found. No changes to commit."
                  fi
              env:
                  SYMBOL: ${{ vars.SYMBOL }}
                  CURRENCY: ${{ vars.CURRENCY }}
                  COST: ${{ vars.COST }}
