name: Automated Monthly Investment

on:
    schedule:
        - cron: "15 7 1 * *" # Runs monthly at 7:15 AM UTC on the 1st
    workflow_dispatch:

jobs:
    run_script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
                  cache: "pip"
                  cache-dependency-path: requirements.txt

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt

            - name: Run the script and capture output
              id: run_script
              run: |
                  # Run the script and capture only stdout
                  output=$(python src/main.py $SYMBOL $CURRENCY $COST)
                  # Define the JSON file name
                  file_name="${SYMBOL}-${CURRENCY}-orders.json"
                  # Save the JSON output to the file
                  echo "$output" > "$file_name"
                  # Export the file name for subsequent steps
                  echo "file_name=$file_name" >> $GITHUB_ENV
              env:
                  SYMBOL: ${{ vars.SYMBOL }}
                  CURRENCY: ${{ vars.CURRENCY }}
                  COST: ${{ vars.COST }}
              continue-on-error: true # Allow workflow to continue even if this step fails

            - name: Handle Script Failure
              if: failure()
              run: |
                  echo "The script failed. Logging the error output."
                  # No JSON file was created, so attempt to log relevant information
                  echo "Check the workflow logs for detailed error messages."
                  exit 1  # Ensure the workflow fails

            - name: Commit and Push JSON File
              if: success()
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add "${{ env.file_name }}"
                  git commit -m "Add order details for ${{ vars.SYMBOL }}-${{ vars.CURRENCY }}"
                  git push origin main
