name: Automated Monthly Investment

on:
    schedule:
        - cron: "45 6 1 * *" # Runs monthly at 6:45 AM UTC on the 1st
    workflow_dispatch:

jobs:
    investment:
        runs-on: ubuntu-latest
        env:
          MERCADO_BITCOIN_API_ID: ${{ secrets.MERCADO_BITCOIN_API_ID }}
          MERCADO_BITCOIN_API_SECRET: ${{ secrets.MERCADO_BITCOIN_API_SECRET }}
          SYMBOL: ${{ vars.SYMBOL }}
          CURRENCY: ${{ vars.CURRENCY }}
          COST: ${{ vars.COST }}
        steps:
            - name: Checkout Repository
            - uses: actions/checkout@v4

            - name: Set Up Python Environment
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"

            - name: Install Dependencies
              run: |
                  pip install --upgrade pip && -r requirements.txt

            - name: Run Investment Script
              run: |
                  python ./src/main.py $SYMBOL $CURRENCY $COST

            - name: Commit and Push JSON File
              if: success()
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

                  file_name="${SYMBOL}-${CURRENCY}-orders.json"
                  file_path="./data/$file_name"

                  # Check if the file exists before adding it to the repository
                  if [ -f "$file_path" ]; then
                    echo "Found $file_path. Adding to git."
                    git add "$file_path"
                    git commit -m "Add order details for ${SYMBOL}-${CURRENCY}"
                    git push origin main
                  else
                    echo "JSON file $file_path not found. No changes to commit."
                  fi
