name: Monthly Investment

on:
    schedule:
        - cron: "15 7 1 * *"
    workflow_dispatch:

jobs:
    run_script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
                  cache: "pip"
                  cache-dependency-path: requirements.txt
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt 1
            - name: Set up environment variables
              run: |
                  echo "TAPI_ID=${{ secrets.TAPI_ID }}" >> $GITHUB_ENV
                  echo "TAPI_SECRET=${{ secrets.TAPI_SECRET }}" >> $GITHUB_ENV
            - name: Run the script
              run: |
                  cd src
                  python main.py ${{ env.SYMBOL }} ${{ env.CURRENCY }} ${{ env.COST }}
