name: Automated Monthly Investment

on:
    schedule:
        - cron: "15 7 1 * *" # Runs monthly at 7:15 AM UTC on the 1st
    workflow_dispatch:

jobs:
    run_script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
                  cache: "pip"
                  cache-dependency-path: requirements.txt
            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
            - name: Set up environment variables
              run: |
                  echo "MERCADO_BITCOIN_API_ID=${{ secrets.MERCADO_BITCOIN_API_ID }}" >> $GITHUB_ENV
                  echo "MERCADO_BITCOIN_API_SECRET=${{ secrets.MERCADO_BITCOIN_API_SECRET }}" >> $GITHUB_ENV
            - name: Run the script
              run: |
                  python ./src/main.py $SYMBOL $CURRENCY $COST
              env:
                  SYMBOL: ${{ vars.SYMBOL }}
                  CURRENCY: ${{ vars.CURRENCY }}
                  COST: ${{ vars.COST }}
