name: Monthly Investment

on:
    schedule:
        - cron: "15 7 1 * *"
    workflow_dispatch:

jobs:
    run_script:
        runs-on: ubuntu-latest
        env:
            # Use the defined environment variables here
            SYMBOL: ${{ env.SYMBOL }}
            CURRENCY: ${{ env.CURRENCY }}
            COST: ${{ env.COST }}
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python environment
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"
            - name: Set environment variables (optional)
              # This step is optional and can be removed if preferred
              run: |
                  echo "Using provided environment variables..."
            - name: Run the script
              run: |
                  cd src
                  python main.py $SYMBOL $CURRENCY $COST
